'use strict';

/**
 * tests/unit/normalization.test.js
 *
 * UNIT TEST: The v1 critical bug fix — per-clip normalisation before concat.
 *
 * This test feeds the render pipeline THREE clips of DIFFERENT resolutions
 * and frame rates, confirms the output is produced successfully, and verifies
 * the output has the correct target dimensions/fps.
 *
 * Failure mode this catches:
 *   v1 used FFmpeg's concat demuxer (stream-copy approach) which silently
 *   produced corrupt or mismatched-stream outputs when clip resolutions/fps
 *   differed — leading to ~1-in-3 render success rate depending on whether
 *   clips happened to share resolution.
 *
 * Source clips (generated by scripts/generate_test_clips.sh):
 *   clip_720_24fps.mp4   — 1280×720 @ 24fps
 *   clip_768_60fps.mp4   — 1366×768 @ 60fps
 *   clip_1080_30fps.mp4  — 1920×1080 @ 30fps
 */

const path = require('path');
const os = require('os');
const fsp = require('fs/promises');
const fs = require('fs');

// Must set env before importing config
process.env.WORKER_API_KEY = 'test-key';
process.env.URL_ALLOWLIST = '';
process.env.TEMP_DIR = os.tmpdir() + '/norm-test-tmp';
process.env.OUTPUT_DIR = os.tmpdir() + '/norm-test-out';
process.env.JOB_TIMEOUT_SECONDS = '120';
process.env.MAX_CLIPS = '60';
process.env.MAX_DURATION_SECONDS = '600';
process.env.MAX_DOWNLOAD_BYTES = String(2 * 1024 * 1024 * 1024);
process.env.DOWNLOAD_TIMEOUT_SECONDS = '60';
process.env.JOB_ATTEMPTS = '1';
process.env.JOB_BACKOFF_DELAY_MS = '1'; // > 0 required by config validation

const FIXTURES = path.resolve(__dirname, '../fixtures/clips');
const TARGET_WIDTH = 1280;
const TARGET_HEIGHT = 720;
const TARGET_FPS = 30;

const { assertVideoProperties, assertFileNonEmpty } = require('../helpers/ffprobeHelpers');

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Builds a minimal BullMQ-like job mock for testing renderJob directly,
 * without needing a real Redis connection.
 */
function makeMockJob(jobId, payload) {
  const data = { ...payload };
  return {
    id: jobId,
    data,
    progress: 0,
    attemptsMade: 0,
    timestamp: Date.now(),
    updateData: async (d) => { Object.assign(data, d); },
    updateProgress: async (p) => { data._progress = p; },
    getState: async () => 'active',
    failedReason: null,
  };
}

/**
 * Generates a synthetic clip using FFmpeg and returns its path.
 * Falls back gracefully if the pre-generated fixture exists.
 */
function clipPath(filename) {
  const p = path.join(FIXTURES, filename);
  if (!fs.existsSync(p)) {
    throw new Error(
      `Test fixture not found: ${p}\n` +
      `Run: bash scripts/generate_test_clips.sh\n` +
      `then re-run the tests.`
    );
  }
  return p;
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('Normalisation filter chain (v1 bug fix)', () => {
  let outputPath;

  beforeAll(async () => {
    await fsp.mkdir(process.env.TEMP_DIR, { recursive: true });
    await fsp.mkdir(process.env.OUTPUT_DIR, { recursive: true });
  });

  afterAll(async () => {
    // Clean up test output
    if (outputPath) {
      try { await fsp.rm(outputPath, { force: true }); } catch { /* ignore */ }
    }
  });

  test(
    'renders three clips of DIFFERENT resolutions/fps into a single correct output — ' +
    '(1280×720@24fps + 1366×768@60fps + 1920×1080@30fps) → 1280×720@30fps',
    async () => {
      const { processRenderJob } = require('../../src/renderJob');

      const clip1 = clipPath('clip_720_24fps.mp4');
      const clip2 = clipPath('clip_768_60fps.mp4');
      const clip3 = clipPath('clip_1080_30fps.mp4');
      const audio  = clipPath('audio_voiceover.mp3');

      const jobId = `norm-test-${Date.now()}`;

      const payload = {
        job_id: jobId,
        clips: [
          { clip_url: `file://${clip1}`, start: 0, end: 3 },
          { clip_url: `file://${clip2}`, start: 0, end: 3 },
          { clip_url: `file://${clip3}`, start: 0, end: 3 },
        ],
        audio_url: `file://${audio}`,
        width: TARGET_WIDTH,
        height: TARGET_HEIGHT,
        fps: TARGET_FPS,
        aspect_ratio: '16:9',
        transition: 'hard-cut',
        transition_duration: 0.5,
        format: 'mp4',
        output_upload_url: null, // use local OUTPUT_DIR fallback
      };

      const job = makeMockJob(jobId, payload);

      // This must not throw
      await expect(processRenderJob(job)).resolves.toBeDefined();

      // Verify output file
      outputPath = path.join(process.env.OUTPUT_DIR, `${jobId}.mp4`);
      await assertFileNonEmpty(outputPath);
      await assertVideoProperties(outputPath, {
        width: TARGET_WIDTH,
        height: TARGET_HEIGHT,
        fps: TARGET_FPS,
      });
    }
  );

  test(
    'renders three mismatched clips with crossfade transition successfully',
    async () => {
      const { processRenderJob } = require('../../src/renderJob');

      const clip1 = clipPath('clip_720_24fps.mp4');
      const clip2 = clipPath('clip_768_60fps.mp4');
      const clip3 = clipPath('clip_1080_30fps.mp4');
      const audio  = clipPath('audio_voiceover.mp3');

      const jobId = `norm-xfade-test-${Date.now()}`;

      const payload = {
        job_id: jobId,
        clips: [
          { clip_url: `file://${clip1}`, start: 0, end: 3 },
          { clip_url: `file://${clip2}`, start: 0, end: 3 },
          { clip_url: `file://${clip3}`, start: 0, end: 3 },
        ],
        audio_url: `file://${audio}`,
        width: TARGET_WIDTH,
        height: TARGET_HEIGHT,
        fps: TARGET_FPS,
        aspect_ratio: '16:9',
        transition: 'crossfade',
        transition_duration: 0.5,
        format: 'mp4',
        output_upload_url: null,
      };

      const job = makeMockJob(jobId, payload);
      await expect(processRenderJob(job)).resolves.toBeDefined();

      const xfOutputPath = path.join(process.env.OUTPUT_DIR, `${jobId}.mp4`);
      await assertFileNonEmpty(xfOutputPath);
      await assertVideoProperties(xfOutputPath, {
        width: TARGET_WIDTH,
        height: TARGET_HEIGHT,
        fps: TARGET_FPS,
      });

      // Cleanup
      await fsp.rm(xfOutputPath, { force: true });
    }
  );
});

describe('Payload validation', () => {
  const { validatePayload } = require('../../src/renderJob');

  const basePayload = {
    clips: [{ clip_url: 'https://videos.pexels.com/a.mp4', start: 0, end: 5 }],
    audio_url: 'https://videos.pexels.com/a.mp3',
    width: 1920,
    height: 1080,
    fps: 30,
    aspect_ratio: '16:9',
    transition: 'hard-cut',
    transition_duration: 0.5,
    format: 'mp4',
  };

  test('valid payload returns null', () => {
    expect(validatePayload(basePayload)).toBeNull();
  });

  test('rejects empty clips array', () => {
    expect(validatePayload({ ...basePayload, clips: [] })).toMatch(/non-empty/);
  });

  test('rejects clip count exceeding MAX_CLIPS', () => {
    const manyClips = Array.from({ length: 100 }, (_, i) => ({
      clip_url: `https://videos.pexels.com/${i}.mp4`, start: 0, end: 5,
    }));
    expect(validatePayload({ ...basePayload, clips: manyClips })).toMatch(/MAX_CLIPS/);
  });

  test('rejects total duration exceeding MAX_DURATION_SECONDS', () => {
    const longClips = Array.from({ length: 5 }, () => ({
      clip_url: 'https://videos.pexels.com/x.mp4', start: 0, end: 200,
    }));
    expect(validatePayload({ ...basePayload, clips: longClips })).toMatch(/MAX_DURATION/);
  });

  test('rejects unsupported transition', () => {
    expect(validatePayload({ ...basePayload, transition: 'wipe-left' })).toMatch(/transition must be/);
  });

  test('rejects end <= start', () => {
    expect(validatePayload({
      ...basePayload,
      clips: [{ clip_url: 'https://videos.pexels.com/a.mp4', start: 5, end: 3 }],
    })).toMatch(/end must be greater than start/);
  });

  test('rejects missing audio_url', () => {
    expect(validatePayload({ ...basePayload, audio_url: '' })).toMatch(/audio_url/);
  });
});

describe('SSRF allowlist guard', () => {
  const { assertAllowedUrl } = require('../../src/downloader');

  beforeAll(() => {
    process.env.URL_ALLOWLIST = 'videos.pexels.com,cdn.pixabay.com';
    // Re-require config to pick up the new env
    jest.resetModules();
  });

  afterAll(() => {
    process.env.URL_ALLOWLIST = '';
    jest.resetModules();
  });

  test('allows a URL on the allowlist', () => {
    // Re-require after resetModules
    const { assertAllowedUrl: check } = require('../../src/downloader');
    expect(() => check('https://videos.pexels.com/path/to/video.mp4')).not.toThrow();
  });

  test('blocks an internal IP (metadata endpoint)', () => {
    const { assertAllowedUrl: check } = require('../../src/downloader');
    expect(() => check('http://169.254.169.254/latest/meta-data/')).toThrow(/SSRF_BLOCK/);
  });

  test('blocks localhost', () => {
    const { assertAllowedUrl: check } = require('../../src/downloader');
    expect(() => check('http://localhost:6379/')).toThrow(/SSRF_BLOCK/);
  });

  test('blocks a host not on the allowlist', () => {
    const { assertAllowedUrl: check } = require('../../src/downloader');
    expect(() => check('https://evil.example.com/payload.mp4')).toThrow(/SSRF_BLOCK/);
  });

  test('allows a subdomain of an allowlisted host', () => {
    const { assertAllowedUrl: check } = require('../../src/downloader');
    expect(() => check('https://subdomain.videos.pexels.com/clip.mp4')).not.toThrow();
  });
});
