// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";
import { getOrCreateTrustedClientToken, TRUSTED_CLIENT_HEADER } from "@/lib/trusted-client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    const clientToken = token ? getOrCreateTrustedClientToken() : null;
    return next({
      headers: token
        ? {
            Authorization: `Bearer ${token}`,
            ...(clientToken ? { [TRUSTED_CLIENT_HEADER]: clientToken } : {}),
          }
        : {},
    });
  },
);
