/**
 * Property-based tests for `cancelRenderJob` handler
 *
 * Feature: render-pipeline-reliability, Property 7: Cancelled job status is always 'cancelled', not 'failed'
 *
 * Strategy: same mock-createServerFn builder-chain pattern as render.test.ts —
 * capture the handler before the module loads, then invoke it with arbitrary
 * jobIds generated by fast-check.
 *
 * Validates: Requirements 3.5, 3.9, 3.10
 */

import { describe, it, expect, vi, beforeAll, beforeEach, afterEach } from "vitest";
import * as fc from "fast-check";

// ─── Module-level captured handler ───────────────────────────────────────────

let capturedHandler:
  | ((args: {
      data: { jobId: string };
      context: { supabase: unknown; userId: string };
    }) => Promise<unknown>)
  | null = null;

// ─── Mock @tanstack/react-start ───────────────────────────────────────────────
vi.mock("@tanstack/react-start", () => {
  const builder = {
    middleware: () => builder,
    inputValidator: () => builder,
    handler: (fn: unknown) => {
      capturedHandler = fn as typeof capturedHandler;
      return builder;
    },
  };
  return {
    createServerFn: () => builder,
  };
});

// ─── Mock requireSupabaseAuth ─────────────────────────────────────────────────
vi.mock("@/integrations/supabase/auth-middleware", () => ({
  requireSupabaseAuth: {},
}));

// ─── supabaseAdmin mock (dynamic import) ─────────────────────────────────────
// We capture the update payload so property assertions can inspect it.
let capturedRenderJobsUpdatePayload: Record<string, unknown> | null = null;
const mockRenderJobsUpdate = vi.fn();
const mockProjectsUpdate = vi.fn();

vi.mock("@/integrations/supabase/client.server", () => ({
  supabaseAdmin: {
    from: (table: string) => {
      if (table === "render_jobs") {
        return {
          update: (vals: unknown) => {
            capturedRenderJobsUpdatePayload = vals as Record<string, unknown>;
            return {
              eq: (_col: string, _val: string) => ({
                in: (_col2: string, _vals: unknown[]) =>
                  mockRenderJobsUpdate(vals),
              }),
            };
          },
        };
      }
      if (table === "projects") {
        return {
          update: (vals: unknown) => ({
            eq: (_col: string, _val: string) => mockProjectsUpdate(vals),
          }),
        };
      }
      throw new Error(`Unexpected table: ${table}`);
    },
  },
}));

// ─── Env vars for workerBase() / workerKey() ─────────────────────────────────
const WORKER_URL = "https://worker.example.com";
const WORKER_KEY = "test-api-key";

// ─── Load the module under test AFTER mocks are set up ───────────────────────
// Trigger module load; handler capture happens at import time via the mock builder.
import("../render.functions");

// ─────────────────────────────────────────────────────────────────────────────

describe("cancelRenderJob — Property 7: Cancelled job status is always 'cancelled', not 'failed'", () => {
  const USER_ID = "user-property-test";

  /** Build a fake user-scoped supabase client that returns a valid job for any jobId */
  function makeMockSupabase(jobId: string) {
    const job = {
      id: jobId,
      project_id: "11111111-2222-3333-4444-555555555555",
      status: "rendering",
      projects: { user_id: USER_ID },
    };
    return {
      from: (_table: string) => ({
        select: (_cols: string) => ({
          eq: (_col: string, _val: string) => ({
            maybeSingle: async () => ({ data: job, error: null }),
          }),
        }),
      }),
    };
  }

  async function callHandler(jobId: string) {
    if (!capturedHandler) {
      throw new Error("Handler was not captured — check createServerFn mock");
    }
    return capturedHandler({
      data: { jobId },
      context: { supabase: makeMockSupabase(jobId), userId: USER_ID },
    });
  }

  beforeAll(async () => {
    // Ensure module is fully loaded and handler is captured
    await import("../render.functions");
  });

  beforeEach(() => {
    process.env.RENDER_WORKER_URL = WORKER_URL;
    process.env.RENDER_WORKER_API_KEY = WORKER_KEY;
    vi.resetAllMocks();
    capturedRenderJobsUpdatePayload = null;
  });

  afterEach(() => {
    delete process.env.RENDER_WORKER_URL;
    delete process.env.RENDER_WORKER_API_KEY;
  });

  // ─── Property 7 ──────────────────────────────────────────────────────────
  // Feature: render-pipeline-reliability, Property 7: Cancelled job status is always 'cancelled', not 'failed'
  it(
    "Property 7: for any valid UUID jobId, cancelRenderJob writes status='cancelled' to render_jobs, NEVER 'failed'",
    async () => {
      expect(capturedHandler).not.toBeNull();

      await fc.assert(
        fc.asyncProperty(fc.uuid(), async (jobId) => {
          // Reset captured state before each run
          capturedRenderJobsUpdatePayload = null;
          mockRenderJobsUpdate.mockResolvedValueOnce({});
          mockProjectsUpdate.mockResolvedValueOnce({});

          // Worker returns success for every arbitrary jobId
          global.fetch = vi.fn().mockResolvedValueOnce({
            ok: true,
            text: async () => "",
          } as Response);

          const result = await callHandler(jobId);

          // 1. The function returns ok: true
          expect((result as { ok: boolean }).ok).toBe(true);

          // 2. render_jobs was updated exactly once
          expect(mockRenderJobsUpdate).toHaveBeenCalledOnce();

          // 3. The status written to render_jobs MUST be 'cancelled'
          const updateArg = mockRenderJobsUpdate.mock.calls[0][0] as Record<
            string,
            unknown
          >;
          expect(updateArg.status).toBe("cancelled");

          // 4. The status written to render_jobs MUST NOT be 'failed'
          expect(updateArg.status).not.toBe("failed");

          // 5. completed_at must be present (ISO timestamp)
          expect(typeof updateArg.completed_at).toBe("string");
          expect((updateArg.completed_at as string).length).toBeGreaterThan(0);

          // Reset mocks for next iteration
          vi.resetAllMocks();
          capturedRenderJobsUpdatePayload = null;
        }),
        { numRuns: 100, verbose: false },
      );
    },
  );
});
